# Generated by Django 3.2.20 on 2023-08-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
