# Generated by Django 3.2.20 on 2023-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviewed',
            field=models.ManyToManyField(blank=True, related_name='reviewed', to='restaurants.Restaurant'),
        ),
    ]
