# Generated by Django 3.2.20 on 2023-08-28 11:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230821_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dif9bjzee/image/upload/ar_1:1,b_rgb:262c35,bo_5px_solid_rgb:2c3e50,c_fill,g_auto,r_max,w_200/v1689590568/profile-gda8c660e4_640_z54qoi.webp', max_length=255, null=True, verbose_name='image'),
        ),
    ]
