# Generated by Django 3.2.20 on 2023-08-19 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=models.TextField(default='Type in a review here...', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
