# Generated by Django 3.2.20 on 2023-08-21 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
